name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH Client
        run: sudo apt-get install openssh-client
      
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /var/www/orderandmenu.com
            git pull origin main
            composer install
            php artisan optimize:clear
            php artisan mirgate
            php artisan db:seed
